name: EAS Update & refresh QR

on:
  push:
    branches: [main]

jobs:
  ota-and-readme:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      CI: 1 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'

      - name: Install Expo/EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest

      - name: Install JS deps
        run: yarn install --frozen-lockfile

      - name: Publish update on branch "main"
        run: npx eas update --auto --branch main --message "${{ github.sha }}"

      - name: Extract Expo URL
        id: expo-url
        run: |
          URL=$(jq -r '.expo.updates.url' app.json)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Generate base64 QR
        run: |
          yarn add --silent qrcode
          node - <<'EOF'
          const fs = require('fs');
          const QRCode = require('qrcode');
          const url = process.env.QR_URL;
          QRCode.toDataURL(url).then(data => fs.writeFileSync('qr64.txt', data));
          EOF
        env:
          QR_URL: ${{ steps.expo-url.outputs.url }}

      - name: Update README
        run: |
          QR=$(cat qr64.txt)
          sed -i 's|!\[Expo QR\](.*)|![Expo QR]('"$QR"')|g' README.md

      - name: Set up git auth for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/alexiskon/farm-notes.git

      - name: Commit README if changed
        run: |
          git config user.name "Alexandros Kontos"
          git config user.email "alexiskon@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "docs: refresh Expo QR for ${{ github.sha }}"
          git push origin main
