name: Publish Expo preview

on:
  push:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_PROJECT_ID: 6811dcaf-2195-4a0e-ba6b-b561e60da885

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install jq (for parsing JSON)
        run: sudo apt-get install -y jq

      - name: Ensure README.md exists
        run: |
          if [ ! -f README.md ]; then
            echo "# Farm Notes" > README.md
          fi

      - name: Publish update to 'main' channel
        id: publish
        run: |
          OUTPUT=$(eas update --branch main --auto --non-interactive --json --message "CI update $GITHUB_SHA")
          echo "$OUTPUT" > update.json
          UPDATE_ID=$(jq -r '.[0].id' update.json)
          echo "UPDATE_ID=$UPDATE_ID" >> "$GITHUB_OUTPUT"

      - name: Generate QR code URL
        id: get_qr
        run: |
          QR_URL="https://qr.expo.dev/eas-update?updateId=${{ steps.publish.outputs.UPDATE_ID }}"
          echo "QR_URL=$QR_URL" >> "$GITHUB_OUTPUT"

      - name: Update README.md with QR code
        run: |
          QR_URL="${{ steps.get_qr.outputs.QR_URL }}"
          FILE=README.md

          if grep -q '<!-- EXPO_QR_START -->' "$FILE"; then
            sed -i "/<!-- EXPO_QR_START -->/,/<!-- EXPO_QR_END -->/c\\
            <!-- EXPO_QR_START -->\\
            ## Live preview\\
            \\
            ![Scan in Expo Go](${QR_URL})\\
            <!-- EXPO_QR_END -->
            " "$FILE"
          else
            echo -e "\n<!-- EXPO_QR_START -->\n## Live preview\n\n![Scan in Expo Go](${QR_URL})\n<!-- EXPO_QR_END -->" >> "$FILE"
          fi

      - name: Configure Git
        run: |
          git config user.name "Alexandros Kontos"
          git config user.email "alexiskon@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alexiskon/farm-notes.git

      - name: Commit README.md if QR changed
        run: |
          git diff --quiet || {
            git add README.md
            git commit -m "Update QR code for latest Expo preview"
            git push
          }
